version: '3'

services:
  back:
    build: ./backend
    volumes:
      - ./backend/php:/src
  front:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app:cached
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "8080:8080"
  nginx:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src
  db:
    build: ./mysql
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store: