version: '3'

services:
  back:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  front:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/:cached
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "8080:8080"
  db:
    image: postgres
    ports: 
        - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - back