# Generated by Django 3.1.4 on 2021-01-04 08:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('city_name', models.CharField(max_length=20, verbose_name='市区町村名')),
                ('city_name_ruby', models.CharField(max_length=50, verbose_name='市区町村名カナ')),
            ],
            options={
                'verbose_name': '市区町村マスタ',
                'db_table': 'm_cities',
            },
        ),
        migrations.CreateModel(
            name='MasterPrefectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prefecture_name', models.CharField(max_length=20, verbose_name='都道府県名')),
                ('prefecture_name_ruby', models.CharField(max_length=50, verbose_name='都道府県名カナ')),
            ],
            options={
                'verbose_name': '都道府県マスタ',
                'db_table': 'm_prefectures',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='店名')),
                ('adress_detail', models.CharField(max_length=50, verbose_name='住所詳細')),
                ('adress_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mastercities', to_field='city_code')),
                ('adress_prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.masterprefectures', to_field='prefecture_code')),
            ],
            options={
                'verbose_name': 'shops',
                'db_table': 'shops',
            },
        ),
        migrations.AddField(
            model_name='mastercities',
            name='prefecture_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.masterprefectures', to_field='prefecture_code'),
        ),
    ]
