# Generated by Django 3.1.5 on 2021-01-31 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCity',
            fields=[
                ('city_code', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=20, verbose_name='市区町村名')),
                ('city_name_ruby', models.CharField(max_length=50, verbose_name='市区町村名カナ')),
            ],
            options={
                'verbose_name': '市区町村マスタ',
                'db_table': 'm_city',
            },
        ),
        migrations.CreateModel(
            name='MasterPrefecture',
            fields=[
                ('prefecture_code', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('prefecture_name', models.CharField(max_length=20, verbose_name='都道府県名')),
                ('prefecture_name_ruby', models.CharField(max_length=50, verbose_name='都道府県名カナ')),
            ],
            options={
                'verbose_name': '都道府県マスタ',
                'db_table': 'm_prefecture',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('adress_detail', models.CharField(max_length=100, verbose_name='住所詳細')),
                ('nearest_station', models.CharField(max_length=100, verbose_name='最寄駅')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adress_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mastercity')),
                ('adress_prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.masterprefecture')),
            ],
            options={
                'verbose_name': '店',
                'db_table': 'shop',
            },
        ),
        migrations.AddField(
            model_name='mastercity',
            name='prefecture_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.masterprefecture'),
        ),
    ]
