# Generated by Django 3.1.4 on 2021-02-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCity',
            fields=[
                ('city_code', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('city_name_ruby', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'm_city',
            },
        ),
        migrations.CreateModel(
            name='MasterPrefecture',
            fields=[
                ('prefecture_code', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('prefecture_name', models.CharField(max_length=20)),
                ('prefecture_name_ruby', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'm_prefecture',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('adress_detail', models.CharField(max_length=100)),
                ('nearest_station', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adress_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mastercity')),
                ('adress_prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.masterprefecture')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.AddField(
            model_name='mastercity',
            name='prefecture_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.masterprefecture'),
        ),
    ]
