# Generated by Django 3.1.5 on 2021-01-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210130_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterCities',
            new_name='MasterCity',
        ),
        migrations.RenameModel(
            old_name='MasterPrefectures',
            new_name='MasterPrefecture',
        ),
    ]
